apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "image-gallery.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-gallery.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  S3_BUCKET_NAME: {{ .Values.config.s3Bucket | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  MAX_UPLOAD_SIZE: {{ .Values.config.maxUploadSize | quote }}
  ALLOWED_EXTENSIONS: {{ .Values.config.allowedExtensions | quote }}
