{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "image-gallery.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-gallery.labels" . | nindent 4 }}
    {{- with .Values.metrics.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "image-gallery.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.metrics.port | default "http" }}
    path: {{ .Values.metrics.path | default "/metrics" }}
    interval: {{ .Values.metrics.interval | default "30s" }}
    {{- with .Values.metrics.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
{{- end }}
