apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: app
  annotations:
    # IRSA - IAM Role ARN from Terraform output
    # Get from: terraform output app_sa_irsa_role_arn
    eks.amazonaws.com/role-arn: arn:aws:iam::184890426414:role/test-dev-app-sa-role
