apiVersion: v1
kind: Service
metadata:
  name: image-gallery
  namespace: app
  labels:
    app: image-gallery
spec:
  type: ClusterIP
  selector:
    app: image-gallery
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
